config/routes.rb
Rails.application.routes.draw do
  resources :dapils
  resources :member_fractions
  resources :structurals
  resources :member_commisions
  resources :fractions do
    collection do
    get 'atur_fraksi' => 'fractions#atur_fraksi', as: :atur_fraksi
    end
  end

  namespace :admin do
      resources :parliaments
  end

  resources :honors
  resources :budgets
  resources :legislations
  resources :commisions
  devise_for :users  #, :path => '', :path_names => {:sign_in => 'sign_in', :sign_out => 'sign_out'}
  resources :parliaments do
    collection { post :upload}
    collection do
      get 'fraksi' => 'parliaments#fraksi', as: :fraksi
      get 'komisi' => 'parliaments#komisi', as: :komisi
    end
  end
  get '/anggota_wakil_rakyat' => 'parliaments#index', as: :anggota_wakil_rakyat

  resources :information
  get '/kegiatan' =>  'information#index', as: :kegiatan

  get '/kontak' => 'boards#kontak', as: :kontak

  get '/alat_dan_kelengkapan' => 'boards#alat_dan_kelengkapan', as: :alat_dan_kelengkapan

  get '/profil' => 'profiles#profil', as: :profil
  get '/sejarah' => 'profiles#sejarah', as: :sejarah
  get '/visi_misi' => 'profiles#visi_misi', as: :visi_misi
  get '/hak_kewajiban' => 'profiles#hak_kewajiban', as: :hak_kewajiban
  get '/tugas_wewenang' => 'profiles#tugas_wewenang', as: :tugas_wewenang

  root 'information#home'

end

app/models/honor.rb
# == Schema Information
#
# Table name: honors
#
#  id            :integer          not null, primary key
#  parliament_id :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Honor < ActiveRecord::Base
end

app/controllers/honors_controller.rb
class HonorsController < ApplicationController
  before_action :set_honor, only: [:show, :edit, :update, :destroy]

  # GET /honors
  # GET /honors.json
  def index
    @honors = Honor.all
  end

  # GET /honors/1
  # GET /honors/1.json
  def show
  end

  # GET /honors/new
  def new
    @honor = Honor.new
  end

  # GET /honors/1/edit
  def edit
  end

  # POST /honors
  # POST /honors.json
  def create
    @honor = Honor.new(honor_params)

    respond_to do |format|
      if @honor.save
        format.html { redirect_to @honor, notice: 'Honor was successfully created.' }
        format.json { render :show, status: :created, location: @honor }
      else
        format.html { render :new }
        format.json { render json: @honor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /honors/1
  # PATCH/PUT /honors/1.json
  def update
    respond_to do |format|
      if @honor.update(honor_params)
        format.html { redirect_to @honor, notice: 'Honor was successfully updated.' }
        format.json { render :show, status: :ok, location: @honor }
      else
        format.html { render :edit }
        format.json { render json: @honor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /honors/1
  # DELETE /honors/1.json
  def destroy
    @honor.destroy
    respond_to do |format|
      format.html { redirect_to honors_url, notice: 'Honor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_honor
      @honor = Honor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def honor_params
      params.require(:honor).permit(:parliament_id)
    end
end

app/helpers/honors_helper.rb
module HonorsHelper
end

app/views/honors/_form.html.erb
<%= simple_form_for(@honor) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :parliament_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/honors/edit.html.erb
<h1>Editing Honor</h1>

<%= render 'form' %>

<%= link_to 'Show', @honor %> |
<%= link_to 'Back', honors_path %>

app/views/honors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Honors</h1>

<table>
  <thead>
    <tr>
      <th>Parliament</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @honors.each do |honor| %>
      <tr>
        <td><%= honor.parliament_id %></td>
        <td><%= link_to 'Show', honor %></td>
        <td><%= link_to 'Edit', edit_honor_path(honor) %></td>
        <td><%= link_to 'Destroy', honor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Honor', new_honor_path %>

app/views/honors/new.html.erb
<h1>New Honor</h1>

<%= render 'form' %>

<%= link_to 'Back', honors_path %>

app/views/honors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Parliament:</strong>
  <%= @honor.parliament_id %>
</p>

<%= link_to 'Edit', edit_honor_path(@honor) %> |
<%= link_to 'Back', honors_path %>