config/routes.rb
Rails.application.routes.draw do
  resources :dapils
  resources :member_fractions
  resources :structurals
  resources :member_commisions
  resources :fractions do
    collection do
    get 'atur_fraksi' => 'fractions#atur_fraksi', as: :atur_fraksi
    end
  end

  namespace :admin do
      resources :parliaments
  end

  resources :honors
  resources :budgets
  resources :legislations
  resources :commisions
  devise_for :users  #, :path => '', :path_names => {:sign_in => 'sign_in', :sign_out => 'sign_out'}
  resources :parliaments do
    collection { post :upload}
    collection do
      get 'fraksi' => 'parliaments#fraksi', as: :fraksi
      get 'komisi' => 'parliaments#komisi', as: :komisi
    end
  end
  get '/anggota_wakil_rakyat' => 'parliaments#index', as: :anggota_wakil_rakyat

  resources :information
  get '/kegiatan' =>  'information#index', as: :kegiatan

  get '/kontak' => 'boards#kontak', as: :kontak

  get '/alat_dan_kelengkapan' => 'boards#alat_dan_kelengkapan', as: :alat_dan_kelengkapan

  get '/profil' => 'profiles#profil', as: :profil
  get '/sejarah' => 'profiles#sejarah', as: :sejarah
  get '/visi_misi' => 'profiles#visi_misi', as: :visi_misi
  get '/hak_kewajiban' => 'profiles#hak_kewajiban', as: :hak_kewajiban
  get '/tugas_wewenang' => 'profiles#tugas_wewenang', as: :tugas_wewenang

  root 'information#home'

end

app/views/shared/_footer.html.erb
<% if params[:controller] == 'information' && params[:action] == 'home' %>
  <footer>
   <div class="row">
    <div class="col-lg-12">
		 <div class="col-lg-3 col-md-6">
      <div class="container">


      	<div class="col-lg-3">
      				<div class="cuadro_intro_hover " style="background-color:#cccccc;">
  						<p style="text-align:center; margin-top:0px;">
                <%= image_tag('gedung_dprd.jpeg', width:'668', height:'439') %>

  						</p>
  						<div class="caption">
  							<div class="blur"></div>
  							<div class="caption-text">
  								<h3 style="border-top:2px solid white; border-bottom:2px solid white; padding:10px;">Info</h3>
  								<p>Loren ipsum dolor si amet ipsum dolor si amet ipsum dolor...</p>
  								<a class=" btn btn-default" href="#"><span class="glyphicon glyphicon-plus"> INFO</span></a>
  							</div>
  						</div>
  					</div>

  	    </div>
         <div class="col-lg-3">
      				<div class="cuadro_intro_hover " style="background-color:#cccccc;">
  						<p style="text-align:center; margin-top:0px;">

  						</p>
  						<div class="caption">
  							<div class="blur"></div>
  							<div class="caption-text">
  								<h3 style="border-top:2px solid white; border-bottom:2px solid white; padding:10px;">Info</h3>
  								<p>Loren ipsum dolor si amet ipsum dolor si amet ipsum dolor...</p>
  								<a class=" btn btn-default" href="#"><span class="glyphicon glyphicon-plus"> INFO</span></a>
  							</div>
  						</div>
  					</div>

  	    </div>


        <div class="col-lg-3 col-md-6">
  			     <h3>Kategori:</h3>
             <ul class="nav nav-pills nav-stacked">
        				<li><a href="#">Tugas Dan Wewenang</a></li>
        				<li><a href="#">Hak Dan Kewajiban</a></li>
        				<li><a href="#">Kegiatan</a></li>
        				<li><a href="#">Produk Hukum</a></li>
  				  </ul>
        </div>

        <div class="col-lg-3 col-md-6">
          <h3>Kontak:</h3>
  				<p>Anda Memiliki Pertanyaan atau Saran? Hubungi Kami!</p>
  				<p><a href="" title="Contact me!" class="email"><i class="fa fa-envelope"></i>&nbsp;Kontak Via Email</a></p>
              <h3>Follow:</h3>


          <a href="" id="gh" target="_blank" title="Twitter" class="twitter"><span class="fa-stack fa-lg">
            <i class="fa fa-square-o fa-stack-2x "></i>
            <i class="fa fa-twitter fa-stack-1x "></i>
            </span>
            Twitter
          </a>
          <a href=""  target="_blank" title="GitHub" class="github"><span class="fa-stack fa-lg">
            <i class="fa fa-square-o fa-stack-2x"></i>
            <i class="fa fa-github fa-stack-1x"></i>
            </span>
            GitHub
          </a>
  			</div>
  			<br/>
        <div id="fb-root"></div>


  <div class="fb-like" data-href="" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>

  <a href="https://twitter.com/share" class="twitter-share-button" data-url="">Tweet</a>
  			<br/>
  			<hr>
        <p>Copyright ©DPRD Kabupaten Bone</p>
  </footer>
<% end %>

app/views/shared/_fraksi_panel.html.erb
<h3 class='lead'>Fraksi</h3>
<ul class="list-group">
  <% @fractions.each do |f| %>
    <% if f.member_fractions.present? %>
      <li class="list-group-item"><%= link_to f.name.upcase, fraction_path(f.id) %></li>
    <% end %>
  <% end %>
</ul>
<% if params[:controller] == 'fractions' && params[:action] == 'show' %>
  <%= link_to 'SEMUA FRAKSI', fractions_path, class:'btn btn-default' %>
<% end %>

app/views/shared/_komisi_panel.html.erb
<h3 class='lead'>Komisi</h3>
<ul class="list-group">
  <% @commisions.each do |c| %>
    <% if c.member_commisions.present? %>
      <li class="list-group-item"><%= link_to c.name.upcase, commision_path(c.id) %></li>
    <% end %>
  <% end %>
</ul>
<% if params[:controller] == 'commisions' && params[:action] == 'show' %>
  <%= link_to 'SEMUA KOMISI', commisions_path, class:'btn btn-default' %>
<% end %>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">DPRD Bone</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= params[:controller]=='information' && params[:action]=='home' ? 'active' : '' %>"><%= link_to "Beranda", root_url %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profil <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Fungsi", "#" %></li>
            <li><%= link_to "Sejarah", "#" %></li>
            <li><%= link_to "Tugas Dan Wewenang", "#" %></li>
            <li><%= link_to "Hak Dan Kewajiban", "#" %></li>
          </ul>
        </li>
        <li class="dropdown
        <%= params[:controller]=='boards'? 'active' : '' %>
        ">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Wakil Rakyat <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li class="<%= params[:action]=='alat_dan_kelengkapan' ? 'active' : '' %>"><%= link_to "Anggota", anggota_wakil_rakyat_path %></li>
            <li class="<%= params[:action]=='alat_dan_kelengkapan' ? 'active' : '' %>"><%= link_to "Komisi", commisions_path %></li>
            <li class="<%= params[:action]=='alat_dan_kelengkapan' ? 'active' : '' %>"><%= link_to "Fraksi", fractions_path %></li>
            <li class="<%= params[:action]=='alat_dan_kelengkapan' ? 'active' : '' %>"><%= link_to "Alat Dan Kelengkapan", alat_dan_kelengkapan_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Galeri <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Kegiatan", kegiatan_path %></li>
            <li><%= link_to "Produk Hukum", "#" %></li>

          </ul>
        </li>

        <li><%= link_to "Kontak", kontak_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class='glyphicon glyphicon-cog'></span> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Atur Komisi", commisions_path %></li>
            <li><%= link_to "Atur Jabatan", structurals_path %></li>
            <li><%= link_to "Atur Fraksi", atur_fraksi_fractions_path %></li>
            <li><%= link_to "Atur Dapil", dapils_path %></li>
            <li><%= link_to "Atur Halaman", "#" %></li>
          </ul>
        </li>
        <% if user_signed_in? %>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>