config/routes.rb
Rails.application.routes.draw do
  resources :dapils
  resources :member_fractions
  resources :structurals
  resources :member_commisions
  resources :fractions do
    collection do
    get 'atur_fraksi' => 'fractions#atur_fraksi', as: :atur_fraksi
    end
  end

  namespace :admin do
      resources :parliaments
  end

  resources :honors
  resources :budgets
  resources :legislations
  resources :commisions
  devise_for :users  #, :path => '', :path_names => {:sign_in => 'sign_in', :sign_out => 'sign_out'}
  resources :parliaments do
    collection { post :upload}
    collection do
      get 'fraksi' => 'parliaments#fraksi', as: :fraksi
      get 'komisi' => 'parliaments#komisi', as: :komisi
    end
  end
  get '/anggota_wakil_rakyat' => 'parliaments#index', as: :anggota_wakil_rakyat

  resources :information
  get '/kegiatan' =>  'information#index', as: :kegiatan

  get '/kontak' => 'boards#kontak', as: :kontak

  get '/alat_dan_kelengkapan' => 'boards#alat_dan_kelengkapan', as: :alat_dan_kelengkapan

  get '/profil' => 'profiles#profil', as: :profil
  get '/sejarah' => 'profiles#sejarah', as: :sejarah
  get '/visi_misi' => 'profiles#visi_misi', as: :visi_misi
  get '/hak_kewajiban' => 'profiles#hak_kewajiban', as: :hak_kewajiban
  get '/tugas_wewenang' => 'profiles#tugas_wewenang', as: :tugas_wewenang

  root 'information#home'

end

app/models/legislation.rb
# == Schema Information
#
# Table name: legislations
#
#  id            :integer          not null, primary key
#  parliament_id :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Legislation < ActiveRecord::Base
end

app/controllers/legislations_controller.rb
class LegislationsController < ApplicationController
  before_action :set_legislation, only: [:show, :edit, :update, :destroy]

  # GET /legislations
  # GET /legislations.json
  def index
    @legislations = Legislation.all
  end

  # GET /legislations/1
  # GET /legislations/1.json
  def show
  end

  # GET /legislations/new
  def new
    @legislation = Legislation.new
  end

  # GET /legislations/1/edit
  def edit
  end

  # POST /legislations
  # POST /legislations.json
  def create
    @legislation = Legislation.new(legislation_params)

    respond_to do |format|
      if @legislation.save
        format.html { redirect_to @legislation, notice: 'Legislation was successfully created.' }
        format.json { render :show, status: :created, location: @legislation }
      else
        format.html { render :new }
        format.json { render json: @legislation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /legislations/1
  # PATCH/PUT /legislations/1.json
  def update
    respond_to do |format|
      if @legislation.update(legislation_params)
        format.html { redirect_to @legislation, notice: 'Legislation was successfully updated.' }
        format.json { render :show, status: :ok, location: @legislation }
      else
        format.html { render :edit }
        format.json { render json: @legislation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /legislations/1
  # DELETE /legislations/1.json
  def destroy
    @legislation.destroy
    respond_to do |format|
      format.html { redirect_to legislations_url, notice: 'Legislation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_legislation
      @legislation = Legislation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def legislation_params
      params.require(:legislation).permit(:parliament_id)
    end
end

app/helpers/legislations_helper.rb
module LegislationsHelper
end

app/views/legislations/_form.html.erb
<%= simple_form_for(@legislation) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :parliament_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/legislations/edit.html.erb
<h1>Editing Legislation</h1>

<%= render 'form' %>

<%= link_to 'Show', @legislation %> |
<%= link_to 'Back', legislations_path %>

app/views/legislations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Legislations</h1>

<table>
  <thead>
    <tr>
      <th>Parliament</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @legislations.each do |legislation| %>
      <tr>
        <td><%= legislation.parliament_id %></td>
        <td><%= link_to 'Show', legislation %></td>
        <td><%= link_to 'Edit', edit_legislation_path(legislation) %></td>
        <td><%= link_to 'Destroy', legislation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Legislation', new_legislation_path %>

app/views/legislations/new.html.erb
<h1>New Legislation</h1>

<%= render 'form' %>

<%= link_to 'Back', legislations_path %>

app/views/legislations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Parliament:</strong>
  <%= @legislation.parliament_id %>
</p>

<%= link_to 'Edit', edit_legislation_path(@legislation) %> |
<%= link_to 'Back', legislations_path %>