config/routes.rb
Rails.application.routes.draw do
  resources :dapils
  resources :member_fractions
  resources :structurals
  resources :member_commisions
  resources :fractions do
    collection do
    get 'atur_fraksi' => 'fractions#atur_fraksi', as: :atur_fraksi
    end
  end

  namespace :admin do
      resources :parliaments
  end

  resources :honors
  resources :budgets
  resources :legislations
  resources :commisions
  devise_for :users  #, :path => '', :path_names => {:sign_in => 'sign_in', :sign_out => 'sign_out'}
  resources :parliaments do
    collection { post :upload}
    collection do
      get 'fraksi' => 'parliaments#fraksi', as: :fraksi
      get 'komisi' => 'parliaments#komisi', as: :komisi
    end
  end
  get '/anggota_wakil_rakyat' => 'parliaments#index', as: :anggota_wakil_rakyat

  resources :information
  get '/kegiatan' =>  'information#index', as: :kegiatan

  get '/kontak' => 'boards#kontak', as: :kontak

  get '/alat_dan_kelengkapan' => 'boards#alat_dan_kelengkapan', as: :alat_dan_kelengkapan

  get '/profil' => 'profiles#profil', as: :profil
  get '/sejarah' => 'profiles#sejarah', as: :sejarah
  get '/visi_misi' => 'profiles#visi_misi', as: :visi_misi
  get '/hak_kewajiban' => 'profiles#hak_kewajiban', as: :hak_kewajiban
  get '/tugas_wewenang' => 'profiles#tugas_wewenang', as: :tugas_wewenang

  root 'information#home'

end

app/models/parliament.rb
# == Schema Information
#
# Table name: parliaments
#
#  id            :integer          not null, primary key
#  name          :string
#  tempat_lahir  :string
#  tanggal_lahir :string
#  dapil_id      :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Parliament < ActiveRecord::Base
has_many :member_fractions
has_many :member_commisions
belongs_to :dapil
belongs_to :legislation


require 'roo'
  # if Rails.env.development?
      # has_attached_file :avatar, styles: { medium: "300x300>", thumb: "50x50>" }, default_url: "unknown_person.png"
      has_attached_file :image, :styles => { :medium => "200x", :thumb => "100x100>" }, :default_url => "default.jpg",
                        :storage => :dropbox,
                        :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
                        :path => "parliaments/:style/:id_filename"
  # end
  # def self.import(file)
  #   #code
  #   Roo::Excelx.create!
  # end

  def self.import(file)
    #code
    allowed_attributes = ["Name","Dapil","Fraksi","Jabatan fraksi"]
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
        row = Hash[[header, spreadsheet.row(i)].transpose]
        parliament = where(name: row["Name"]) || new
        parliament.attributes = row.to_hash.select { |k,v| allowed_attributes.include? k }
        parliament.save!
    end
  end

  def self.open_spreadsheet(file)
    # code
    case File.extname(file.original_filename)
    when '.csv' then Roo::Csv.new(file.path, nil, packed: nil, file_warning: :ignore)
    when '.xls' then Roo::Excel.new("#{Rails.root}/public/Wakil_Rakyat_DPRD_Bone.xls")
    when '.xlsx' then Roo::Excelx.new(file.path, nil, packed: nil, file_warning: :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end

  # def self.import(file)
    #code
    # ex = open_spreadsheet(file)
    # excel_file  = Roo::Excel.new("#{Rails.root}/public/Wakil_Rakyat_DPRD_Bone.xls")
    #  header = excel_file.row(1)

    # ex.default_sheet = ex.sheets[1]

    # header = Hash.new
    # excel_file.row(1).each_with_index{
    #   |header, i| header[header] = 1
    #
    # }

    # ((excel_file.first_row + 2)..excel_file.last_row).each do |row|
        # Get the column data using the column heading.
        # name = excel_file.row(row)[header['Nama']]
        # dapil = excel_file.row(row)[header['Dapil']]
        # fraksi = excel_file.row(row)[header['Fraksi']]
        # @parliaments = Parliament.create(:name => name, :dapil => dapil, :fraksi => fraksi)

        # print "Row: #{name}, #{dapil}, #{fraksi}\n\n"
    # end

    # 2.upto(46) do |line|
    #   name = excel_file.cell(line,'A') if excel_file.cell(line,'A')
    #   dapil = excel_file.cell(line, 'B') if excel_file.cell(line, 'B')
    #   fraksi = excel_file.cell(line,'C') if excel_file.cell(line, 'C')
    #   @parliaments = Parliament.create(:name => name, :dapil => dapil, :fraksi => fraksi)
    # end


    # (2..excel_file.last_row).each do |i|
    #   row = Hash[[header, excel_file.row(i)].transpose]
    #   parliament = find_by_id(row["id"]) || new
    #   parliament.attributes = parliament.hash.slice() #to_hash change to Hash[*a]
    #   parliament.save!
    # end

    # Parliament.each(id: 'ID', name: 'NAME', dapil: 'DAPIL') do |hash|
      # puts hash.inspect
        # => { id: 1, name: 'John Smith' }
    #   end
    # end

  # def open_spreadsheet
  #   #code
  #   case File.extname(file.original_filename)
  #   when ".csv" then Roo::Csv.new(file.path, nil, :ignore)
  #   when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
  #   when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
  #   else raise "unknwon file type: #{(file.original_filename)}"
  # end
 # validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
 # validates_attachment_file_name :avatar, matches: [/png\Z/, /jpe?g\Z/]


 # attr_accessible  :name, :dapil, :fraksi
# def self.import(file)
    # spreadsheet = open_spreadsheet(file)
    # spreadsheet = Roo::Excel.new("#{Rails.root}/public/Wakil_Rakyat_DPRD_Bone.xls")
  #   spreadsheet = Roo::Spreadsheet.open('./rails_temp_upload', extension: :xls)
  #   header = spreadsheet.row(1)
  #   (2..spreadsheet.last_row).each do |i|
  #     row = Hash[[header, spreadsheet.row(i)].transpose]
  #     parliament = Parliament.find_by(name: row["Name"].to_s) || Parliament.new
  #     parliament.attributes = row.to_hash.slice("name", "dapil", "fraksi", "id" )
  #     parliament.save!
  #   end
  # end

  # def self.open_spreadsheet(file)
    # case File.extname(file.original_filename)
    # when ".csv" then Roo::Csv.new(file.path, csv_options: {col_sep: ";"})
    # when ".xls" then Roo::Excel.new("#{Rails.root}/public/Wakil_Rakyat_DPRD_Bone.xls")
    # when ".xlsx" then Roo::Excelx.new(file.path)
    # else raise "Unknown file type: #{file.original_filename}"
    # end
  # end
# def self.import(file)
  #code
# end

end

app/controllers/admin/parliaments_controller.rb
# == Schema Information
#
# Table name: parliaments
#
#  id                       :integer          not null, primary key
#  name                     :string
#  dapil                    :string
#  fraksi                   :string
#  jabatan_fraksi           :string
#  komisi                   :string
#  jabatan_komisi           :string
#  jabatan_badan_anggaran   :string
#  jabatan_badan_musyawarah :string
#  jabatan_badan_kehormatan :string
#  jabatan_badan_legislatif :string
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#

class Admin::ParliamentsController < ApplicationController
  before_action :set_parliament, only: [:show, :edit, :update, :destroy]
  # load_and_authorize_resource
  # before_action :authenticate_user!, except: [:index]

  def upload
    #code
    Parliament.import(params[:file])
    redirect_to :back, notice: "Data Berhasil Diupload"
  end

  # GET /parliaments
  # GET /parliaments.json
  def index
    @fractions = Fraction.all
    @parliaments = Parliament.paginate(:page => params[:page], :per_page => 9)
    @allparliaments = Parliament.order("created_at asc")
    respond_to do |format|
        format.html # don't forget if you pass html
        # format.xls { send_data(@allparliaments.to_xls) }
        format.xls {
          filename = "Wakil_Rakyat_DPRD_Bone.xls"
          urut_tabel = [:name, :dapil, :fraksi, :jabatan_fraksi]
          send_data(@allparliaments.to_xls(:only => urut_tabel), :type => "text/xls; charset=utf-8; header=present", :filename => filename)
        }
    end

  end

  # GET /parliaments/1
  # GET /parliaments/1.json
  def show
  end

  # GET /parliaments/new
  def new
    @parliament = Parliament.new
  end

  # GET /parliaments/1/edit
  def edit
  end

  # POST /parliaments
  # POST /parliaments.json
  def create
    @parliament = Parliament.new(parliament_params)

    respond_to do |format|
      if @parliament.save
        format.html { redirect_to @parliament, notice: 'Parliament was successfully created.' }
        format.json { render :show, status: :created, location: @parliament }
      else
        format.html { render :new }
        format.json { render json: @parliament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parliaments/1
  # PATCH/PUT /parliaments/1.json
  def update
    respond_to do |format|
      if @parliament.update(parliament_params)
        format.html { redirect_to @parliament, notice: 'Parliament was successfully updated.' }
        format.json { render :show, status: :ok, location: @parliament }
      else
        format.html { render :edit }
        format.json { render json: @parliament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parliaments/1
  # DELETE /parliaments/1.json
  def destroy
    @parliament.avatar = nil
    @parliament.destroy
    respond_to do |format|
      format.html { redirect_to parliaments_url, notice: 'Parliament was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def fraksi
    #code
    @parliaments = Parliament.all
    @fractions = Fraction.all
  end

  def komisi
    #code
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parliament
      @parliament = Parliament.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parliament_params
      params.require(:parliament).permit(:name, :dapil, :fraksi, :jabatan_fraksi, :komisi, :jabatan_komisi, :jabatan_badan_anggaran, :jabatan_badan_musyawarah, :jabatan_badan_kehormatan, :jabatan_badan_legislatif, :avatar, :file)
    end
end

app/controllers/parliaments_controller.rb
# == Schema Information
#
# Table name: parliaments
#
#  id                       :integer          not null, primary key
#  name                     :string
#  dapil                    :string
#  fraksi                   :string
#  jabatan_fraksi           :string
#  komisi                   :string
#  jabatan_komisi           :string
#  jabatan_badan_anggaran   :string
#  jabatan_badan_musyawarah :string
#  jabatan_badan_kehormatan :string
#  jabatan_badan_legislatif :string
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#

class ParliamentsController < ApplicationController
  before_action :set_parliament, only: [:show, :edit, :update, :destroy]
  # load_and_authorize_resource
  # before_action :authenticate_user!, except: [:index]

  def upload
    #code
    Parliament.import(params[:file])
    redirect_to :back, notice: "Data Berhasil Diupload"
  end

  # GET /parliaments
  # GET /parliaments.json
  def index
    @fractions = Fraction.all
    # @fraction = Fraction.find(params[:id])
    @parliaments = Parliament.paginate(:page => params[:page], :per_page => 9).order("created_at asc")
    @allparliaments = Parliament.order("created_at asc")
    respond_to do |format|
        format.html # don't forget if you pass html
        # format.xls { send_data(@allparliaments.to_xls) }
        format.xls {
          filename = "Wakil_Rakyat_DPRD_Bone.xls"
          urut_tabel = [:name, :dapil, :fraksi, :jabatan_fraksi]
          send_data(@allparliaments.to_xls(:only => urut_tabel), :type => "text/xls; charset=utf-8; header=present", :filename => filename)
        }
    end

  end

  # GET /parliaments/1
  # GET /parliaments/1.json
  def show
  end

  # GET /parliaments/new
  def new
    @parliament = Parliament.new
  end

  # GET /parliaments/1/edit
  def edit
  end

  # POST /parliaments
  # POST /parliaments.json
  def create
    @parliament = Parliament.new(parliament_params)

    respond_to do |format|
      if @parliament.save
        format.html { redirect_to @parliament, notice: 'Parliament was successfully created.' }
        format.json { render :show, status: :created, location: @parliament }
      else
        format.html { render :new }
        format.json { render json: @parliament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parliaments/1
  # PATCH/PUT /parliaments/1.json
  def update
    respond_to do |format|
      if @parliament.update(parliament_params)
        format.html { redirect_to @parliament, notice: 'Parliament was successfully updated.' }
        format.json { render :show, status: :ok, location: @parliament }
      else
        format.html { render :edit }
        format.json { render json: @parliament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parliaments/1
  # DELETE /parliaments/1.json
  def destroy
    @parliament.avatar = nil
    @parliament.destroy
    respond_to do |format|
      format.html { redirect_to parliaments_url, notice: 'Parliament was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parliament
      @parliament = Parliament.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parliament_params
      params.require(:parliament).permit(:name, :tanggal_lahir, :tempat_lahir, :dapil_id, :avatar, :file)
    end
end

app/helpers/admin/parliaments_helper.rb
module Admin::ParliamentsHelper
end

app/helpers/parliaments_helper.rb
# == Schema Information
#
# Table name: parliaments
#
#  id                       :integer          not null, primary key
#  name                     :string
#  dapil                    :string
#  fraksi                   :string
#  jabatan_fraksi           :string
#  komisi                   :string
#  jabatan_komisi           :string
#  jabatan_badan_anggaran   :string
#  jabatan_badan_musyawarah :string
#  jabatan_badan_kehormatan :string
#  jabatan_badan_legislatif :string
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#

module ParliamentsHelper
end

app/views/parliaments/_form.html.erb
<%= simple_form_for(@parliament) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%#= f.input :avatar, as: :image_preview, input_html: {preview_version: :thumb}, label: "Foto Anggota" %>
    <%= f.input :name, label: "Nama" %>
    <%= f.input :tempat_lahir, label: "Tempat Lahir" %>
    <%= f.input :tanggal_lahir, label: "Tanggal Lahir" %>
    <%= f.association :dapil, label: "Daerah Pilihan ", label_method: :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-success" %>
  </div>
<% end %>

<br>
<br>

app/views/parliaments/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-md-6">
      <h3 class="lead">Edit Anggota Dewan</h3>
      <%= render 'form' %>
      <%= link_to 'Show', @parliament, class:"btn btn-success" %> |
      <%= link_to 'Back', parliaments_path, class: "btn btn-default" %>
      <hr>
    </div>
  </div>
  <br>
</div>

app/views/parliaments/fraksi.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-md-8">
        <% @parliaments.each do |parliament| %>
        <h3 class="lead"><%= parliament.name %></h3>

        <% end %>
    </div>
    <div class="hidden-xs col-sm-4 col-md-4">
      
    </div>
  </div>
</div>

app/views/parliaments/index.html.erb
<div class="container">
  <%# if user_signed_in? %>
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
      <%= link_to 'Tambah Wakil Rakyat', new_parliament_path, class: "btn btn-success" %>
    </div>
  </div>
  <%# end %>
  <br>
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <h3 clas="lead">Daftar Anggota Wakil Rakyat</h3>
    </div>

  </div>
  <div class="row">
    <% @parliaments.each do |parliament| %>
    <div class="col-xs-12 col-sm-12 col-md-12">
      <hr>
    </div>
    <div class="col-xs-4 col-sm-2 col-md-2">
      <%= image_tag("unknown_person.png", size: "100x100") %>
      <%#= image_tag parliament.avatar.url(:thumb) %>
    </div>
    <div class="col-xs-6 col-sm-10 col-md-10 ">
      <div class="row"><strong><%= link_to parliament.name, parliament %></strong></div>
      <div class="row"><strong>Tempat,&nbsp;Tanggal Lahir&nbsp;:</strong>&nbsp;&nbsp;<%= parliament.tempat_lahir %>,&nbsp;<%= parliament.tanggal_lahir %></div>

    </div>
    <% end %>
    <div class="col-xs-12 col-sm-12 col-md-12">
      <%= will_paginate @parliaments, renderer: BootstrapPagination::Rails, class: 'pagination' %>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
      <%= link_to 'Excel Download', parliaments_path(:format => :xls) %>
      <%= form_tag upload_parliaments_path, multipart: true do %>
        <%= file_field_tag :file %>
        <%= submit_tag "Upload Xls" %>
      <% end %>
    </div>
  </div>
  <br>
  <br>




</div>

app/views/parliaments/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-md-6">
      <h3 class="lead">Buat Anggota Dewan</h3>
      <%= render 'form' %>
      <%= link_to 'Back', parliaments_path, class: "btn btn-success" %>
      <hr>
    </div>
  </div>
  <br>
</div>

app/views/parliaments/show.html.erb
<div class="container">
  <div class="col-sm-12 col-md-12 col-xs-12">
    <p>
      <strong>Nama:</strong>
      <%= @parliament.name %>
    </p>

    <p>
      <strong>Tempat, Tanggal Lahir</strong>
      <%= @parliament.tempat_lahir %>, <%= @parliament.tanggal_lahir %>
    </p>

    <p>
      <strong>Dapil:</strong>
      <%= @parliament.dapil.name rescue nil %>
    </p>


  </div>
  <div class="col-sm-12 col-md-12 col-xs-12">
    <%= link_to 'Edit', edit_parliament_path(@parliament), class: "btn btn-warning"%> &nbsp;
    <%= link_to 'Back', parliaments_path, class: "btn btn-default" %>
  </div>
</div>